name: Resume Auto Build
on: [push]
jobs:
  Build-Resume-JSON:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - run: sudo apt-get install jq

      - name: Install requirements.txt
        run: pip install -r ${{ github.workspace }}/requirements.txt
      
      - name: Convert 'resume.yml' to 'resume.json'
        run: cat ${{ github.workspace }}/resume.yml | yq > ${{ github.workspace }}/resume.json
      
      # - name: Display 'resume.json'
      #   run: cat ${{ github.workspace }}/resume.json

      - name: Create resume artifact
        uses: actions/upload-artifact@v2
        with:
          name: resume.json
          path: ${{ github.workspace }}/resume.json

  Resume-Lint:
    needs: Build-Resume-JSON
    runs-on: ubuntu-20.04
    steps:

      - name: Download the resume artifact
        uses: actions/download-artifact@v2
        with:
          name: resume.json
      
      - name: Install Resume CLI
        run: npm install -g resume-cli
      
      - name: Validate Resume Schema
        run: resume validate resume.json

      - run: cat ${{ github.workspace }}/resume.json
